```{r echo=FALSE}

createSEITL <- function(deterministic=TRUE, verbose=TRUE) {

	#########################################################################################
	# First we define all model parameters (theta) using fitparam objects.
	#########################################################################################

	# This is the basic reproduction number, its high value reflect the high contact rate among islanders.
	R0 <- fitparam(name="R0",value=10,support=c(0,Inf),sd.proposal=1,prior=list(distribution="dunif",parameters=c(min=1,max=100)))

	# The latent period
	LatentPeriod <- fitparam(name="LP",value=2,support=c(0,Inf),sd.proposal=0.5,prior=list(distribution="dunif",parameters=c(min=0,max=7)))

	# The infectious period
	InfectiousPeriod <- fitparam(name="IP",value=3,support=c(0,Inf),sd.proposal=0.5,prior=list(distribution="dunif",parameters=c(min=0,max=30)))

	# The duration of the temporary protection against reinfection
	TemporaryImmunePeriod  <- fitparam(name="TIP",value=10,support=c(0,Inf),sd.proposal=2,prior=list(distribution="dunif",parameters=c(min=0,max=50)))

	# The probability to acquire a long-term protection following completion of the temporary immunity
	ProbLongTermImmunity <- fitparam(name="alpha",value=0.5,support=c(0,1),sd.proposal=0.1,prior=list(distribution="dunif",parameters=c(min=0,max=1)))

	# The intensity of the case reporting
	ReportingRate <- fitparam(name="rho",value=0.7,support=c(0,2),sd.proposal=0.1,prior=list(distribution="dunif",parameters=c(min=0,max=2)))

	# The initial proportion of infectious individuals
	proportionI0 <- fitparam(name="pI0",value=2/284,support=c(0,1),sd.proposal=1/284,prior=list(distribution="dunif",parameters=c(min=1/284,max=5/284)))

	# The initial proportion of fully protected individuals
	proportionL0 <- fitparam(name="pL0",value=0.1,support=c(0,1),sd.proposal=0.01,prior=list(distribution="dunif",parameters=c(min=0.0,max=0.5)))

	# The population size (note that this parameter has less arguments since it is fixed)
	PopSize <- fitparam(name="N",value=284)

	#########################################################################################
	# We define the vector of state variable names
	#########################################################################################

	state.variables <- c("S","E","I","T","L","Inc")

	#########################################################################################
	# We load and rename the data to have column names: "time" and "Inc"
	#########################################################################################

	data("FluTdC1971",envir = environment())
	data <- rename(FluTdC1971,c("day"="time","incidence"="Inc"))[c("time","Inc")]

	#########################################################################################
	# Then we choose a simulator (deterministic or stochastic)
	#########################################################################################

	if(deterministic){
		simulate.model <- SEITL_simulateDeterministic
	}else{
		simulate.model <- SEITL_simulateStochastic
	}

	#########################################################################################
	# And finally we create a fitmodel
	# Note that all the functions with names starting by SEITL_ are already coded in the
	# package and can be considered as blackboxes.
	# Of course, feel free to have a look at their code and documentation.
	#########################################################################################

	SEITL <- fitmodel(
		verbose=verbose,
		name="SEITL",
		state.variables=state.variables,
		list.fitparam=list(R0,LatentPeriod,InfectiousPeriod,TemporaryImmunePeriod,ProbLongTermImmunity,ReportingRate,proportionI0,proportionL0,PopSize),
		initialise.state=SEITL_initialiseState,
		log.prior.fitparam=SEITL_logPrior,
		simulate.model=simulate.model,
		generate.observation=SEITL_generateObservation,
		data=data,
		log.likelihood=SEITL_logLikelihood,
		distance.ABC=SEITL_distanceOscillation
		)


	# Return the fitmodel object
	return(SEITL)
}

```

# summary statistics

```{r }
my_summaryStatPeak <- function(time,inc){

	# highest peak
	return(max(inc))
}


my_summaryStatPeakTime <- function(time,inc){
	#
	return(time[max(inc)])
}

my_summaryStatFinalSize <- function(time,inc){

	# final size
	return(sum(inc))
}

my_summaryStatPeak0to20 <- function(time,inc){

	# max inc between day 0 and 20
	return(max(inc[time<20]))
}

my_summaryStatPeakAfter20 <- function(time,inc){

	# max inc between day 0 and 20
	return(max(inc[time>20]))
}

my_summaryStatInc0to20 <- function(time,inc){

	# inc between day 0 and 20
	return(inc[time >= 0 & time <= 20])
}


my_summaryStatInc25to45 <- function(time,inc){

	# inc between day 25 and 45
	return(inc[time >= 25 & time <= 45])
}
```


# Distances


```{r }
my_distance1 <- function(data,simu) {
	# highest peak
	return((data-simu)^2/data)
}


my_distance2 <- function(data,simu) {
	# peak time
	return(abs(data-simu))
}


my_distance3 <- function(data,simu) {
	# final size
	return(abs(data-simu))
}

my_distance4 <- function(data,simu) {
	# peak first wave
	return((data-simu)^2/data)
}

my_distance5 <- function(data,simu) {
	# peak second wave
	return((data-simu)^2/data)
}

my_distance6 <- function(data,simu) {
	# oscillation distance first wave
	return(distanceOscillation(data,simu))
}

my_distance7 <- function(data,simu) {
	# oscillation distance second wave
	return(distanceOscillation(data,simu))
}


```

# ABC acceptance

Just using the 6th and 7th summary and distance

```{r }

ABCacceptance <- function(theta,fitmodel,tol) {

    # simulate model
	simu <- fitmodel$simulate.model(theta=theta, init.state=fitmodel$initialise.state(theta),times=c(0,fitmodel$data$time))

    # generate observation
	simu.obs <- fitmodel$generate.observation(model.traj=simu, theta=theta)
	time.simu <- simu.obs$time[-1] # remove initial time
	inc.simu <- simu.obs$observation[-1] # remove initial state

    # compute data and simulated summary statistics
	# data
	time.data <- fitmodel$data$time
	inc.data <- fitmodel$data$Inc

	ss6.data <- my_summaryStatInc0to20(time=time.data,inc=inc.data)
	ss7.data <- my_summaryStatInc25to45(time=time.data,inc=inc.data)
	# simu
	ss6.simu <- my_summaryStatInc0to20(time=time.simu,inc=inc.simu)
	ss7.simu <- my_summaryStatInc25to45(time=time.simu,inc=inc.simu)


    # compute distances between summary statistics
	d6 <- my_distance6(data=ss6.data,simu=ss6.simu)
	d7 <- my_distance7(data=ss7.data,simu=ss7.simu)

    # check that distances are within the tolerances
    # return 0/1
	if(d6<tol[6] && d7 < tol[7]){
		return(1)
	} else {
		return(0)
	}

}

```

```{r }
# test
library(fitcourseR)

my_SEITL <- createSEITL(deterministic=FALSE, verbose=FALSE)

ABCacceptance(my_SEITL$theta,my_SEITL,tol=c(0,0,0,0,0,10,1))

```
