project:
  type: website
  render:
    - "*.qmd"

bibliography: references.bib

execute:
  freeze: auto

filters:
  - quarto-ext/include-code-files

website:
  title: "MFIIDD"
  site-url: https://mfiidd.github.io/mfiidd/
  repo-url: https://github.com/mfiidd/mfiidd
  repo-actions: [source, issue]
  description: "Model fitting and inference for infectious disease dynamics"
  body-footer: '<script data-goatcounter="https://mfidd.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
  open-graph: true
  favicon: mfiidd-favicon.png
  navbar:
    left:
      - getting-started.qmd
      - sidebar:sessions
      - sidebar:reference
      - authors.qmd
    right:
      - icon: github
        href: https://github.com/mfiidd/mfiidd
  sidebar:
    - id: sessions
      title: "Sessions"
      style: "docked"
      contents:
        - sessions/introduction-and-course-overview.qmd
        - sessions/introduction.qmd
        - sessions/mcmc.qmd
        - sessions/mcmc_diagnostics.qmd
        - sessions/model_checking.qmd
        - sessions/seitl.qmd
        - sessions/particle_filters.qmd
        - sessions/pmcmc.qmd
        - sessions/observation_models.qmd
        - sessions/abc.qmd
        - sessions/variational_inference.qmd
        - sessions/neural_posterior_estimation.qmd
        - sessions/universal_differential_equations.qmd
        - sessions/julia_ecosystem.qmd
    - id: reference
      title: "Reference"
      style: "docked"
      contents: "reference/*.qmd"

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    toc: true
