project:
  type: website
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "MFIIDD"
  site-url: https://sbfnk.github.io/mfiidd.julia/
  repo-url: https://github.com/sbfnk/mfiidd.julia
  repo-actions: [source, issue]
  description: "Model fitting and inference for infectious disease dynamics"
  body-footer: '<script data-goatcounter="https://mfidd.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
  open-graph: true
  navbar:
    left:
      - sidebar:sessions
    right:
      - icon: github
        href: https://github.com/sbfnk/mfiidd.julia
  sidebar:
    - id: sessions
      title: "Sessions"
      style: "docked"
      contents:
        - sessions/getting-started.qmd
        - sessions/structure.qmd
        - sessions/introduction.qmd
        - sessions/mcmc.qmd
        - sessions/mcmc_diagnostics.qmd
        - sessions/model_checking.qmd
        - sessions/seitl.qmd
        - sessions/particle_filters.qmd
        - sessions/pmcmc.qmd
        - sessions/observation_models.qmd
        - sessions/variational_inference.qmd
        - sessions/universal_differential_equations.qmd

format:
  html:
    theme:
      light: brite
      dark: vapor
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    toc: true
